### ISSUE TITLE
@geekcojp/gp@nextでのadd babel後のWebSocketコンソールエラー

### ISSUE THREAD

**Issue by yamanoku** [geekcojp/gp#12]
[![Screenshot from Gyazo](https://gyazo.com/207b69ebc33b55804c90063abd54394d/raw)](https://gyazo.com/207b69ebc33b55804c90063abd54394d)

`gp dev` で走らせているとずっと出る感じです。
fuseboxによるものだと思うんですけども、こちら解消いただけると助かります 🙇 

[![Screenshot from Gyazo](https://gyazo.com/14bf5a426897b0bb09054d629086c659/raw)](https://gyazo.com/14bf5a426897b0bb09054d629086c659)

**Comment by nju33** [comment]
@yamanoku fixed

**Comment by yamanoku** [comment]
👍 
[![Screenshot from Gyazo](https://gyazo.com/fb8dc917a3802e9ae450f527caab73cf/raw)](https://gyazo.com/fb8dc917a3802e9ae450f527caab73cf)
